version: "3.7"

services:
  lemmy:
    image: dessalines/lemmy:0.19.3
    restart: always
    volumes:
      - ./lemmy.hjson:/config/config.hjson:Z
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.3
    depends_on:
      - lemmy
    environment:
     LEMMY_UI_LEMMY_INTERNAL_HOST: lemmy:8536
     LEMMY_UI_CUSTOM_HTML_HEADER: "<script src=\"/oauth-login/assets/oauth-button.js\"></script>"
    restart: always

  pictrs:
    image: asonix/pictrs:0.5.13
    user: 991:991
    volumes:
      - "pictrs_data:/mnt"
    restart: always

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: enter
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  oauth_companion:
    image: golang:1.21.6
    working_dir: /app
    command: ["go", "run", "."]
    volumes:
      - "./:/app"
      - "go_dir:/go"
      - "go_cache:/.cache"
    environment:
      POSTGRES_URL: postgresql://postgres:enter@postgres/postgres?sslmode=disable
      LEMMY_URL: "http://lemmy:8536"
      BASE_URL: "http://localhost:8000"
      COOKIE_SECURE: "false"
    env_file:
     - .env
    depends_on:
     - postgres
     - lemmy
    restart: always

  lemmy-nginx:
    image: nginx:1.25.3
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro,Z"
      - "./proxy_params:/etc/nginx/proxy_params:ro,Z"
    ports:
      - "8000:8536"
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui

volumes:
 postgres_data: {}
 pictrs_data: {}
 go_cache: {}
 go_dir: {}