name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.x

      - name: Test
        run: |
          go test ./... -coverprofile=profile.cov

      - uses: shogo82148/actions-goveralls@v1.8.0
        with:
          path-to-profile: profile.cov

      - name: Log in to the Container registry
        if: success() && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # step for master/latest (docker only)
      - name: Build and push latest docker image
        if: success() && github.ref == 'refs/heads/master'
        run: |
          docker build . -t ghcr.io/minetest-ch/lemmy-oauth-companion:latest
          docker push ghcr.io/minetest-ch/lemmy-oauth-companion:latest
