name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Test
      run: |
        go test ./... -coverprofile=profile.cov

    - uses: shogo82148/actions-goveralls@v1.9.0
      with:
        path-to-profile: profile.cov